/* oisystemOIWebServiceSoapProxy.h
   Generated by gSOAP 2.8.40 for oisystem.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef oisystemOIWebServiceSoapProxy_H
#define oisystemOIWebServiceSoapProxy_H
#include "oisystemH.h"

    class SOAP_CMAC OIWebServiceSoapProxy : public soap {
      public:
        /// Endpoint URL of service 'OIWebServiceSoapProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in oisystem.h, if any
        /// Construct a proxy with new managing context
        OIWebServiceSoapProxy();
        /// Copy constructor
        OIWebServiceSoapProxy(const OIWebServiceSoapProxy& rhs);
        /// Construct proxy given a managing context
        OIWebServiceSoapProxy(const struct soap&);
        /// Constructor taking an endpoint URL
        OIWebServiceSoapProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        OIWebServiceSoapProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        OIWebServiceSoapProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        OIWebServiceSoapProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and managing context
        virtual ~OIWebServiceSoapProxy();
        /// Initializer used by constructors
        virtual void OIWebServiceSoapProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual OIWebServiceSoapProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        OIWebServiceSoapProxy& operator=(const OIWebServiceSoapProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'OIWebServiceCheck' (returns SOAP_OK or error code)
        virtual int OIWebServiceCheck(_ns1__OIWebServiceCheck *ns1__OIWebServiceCheck, _ns1__OIWebServiceCheckResponse &ns1__OIWebServiceCheckResponse)
        { return this->OIWebServiceCheck(NULL, NULL, ns1__OIWebServiceCheck, ns1__OIWebServiceCheckResponse); }
        virtual int OIWebServiceCheck(const char *soap_endpoint, const char *soap_action, _ns1__OIWebServiceCheck *ns1__OIWebServiceCheck, _ns1__OIWebServiceCheckResponse &ns1__OIWebServiceCheckResponse);
        /// Web service operation 'OIWebServiceLotStartCheck' (returns SOAP_OK or error code)
        virtual int OIWebServiceLotStartCheck(_ns1__OIWebServiceLotStartCheck *ns1__OIWebServiceLotStartCheck, _ns1__OIWebServiceLotStartCheckResponse &ns1__OIWebServiceLotStartCheckResponse)
        { return this->OIWebServiceLotStartCheck(NULL, NULL, ns1__OIWebServiceLotStartCheck, ns1__OIWebServiceLotStartCheckResponse); }
        virtual int OIWebServiceLotStartCheck(const char *soap_endpoint, const char *soap_action, _ns1__OIWebServiceLotStartCheck *ns1__OIWebServiceLotStartCheck, _ns1__OIWebServiceLotStartCheckResponse &ns1__OIWebServiceLotStartCheckResponse);
        /// Web service operation 'OIWebEquipmentStatusCheck' (returns SOAP_OK or error code)
        virtual int OIWebEquipmentStatusCheck(_ns1__OIWebEquipmentStatusCheck *ns1__OIWebEquipmentStatusCheck, _ns1__OIWebEquipmentStatusCheckResponse &ns1__OIWebEquipmentStatusCheckResponse)
        { return this->OIWebEquipmentStatusCheck(NULL, NULL, ns1__OIWebEquipmentStatusCheck, ns1__OIWebEquipmentStatusCheckResponse); }
        virtual int OIWebEquipmentStatusCheck(const char *soap_endpoint, const char *soap_action, _ns1__OIWebEquipmentStatusCheck *ns1__OIWebEquipmentStatusCheck, _ns1__OIWebEquipmentStatusCheckResponse &ns1__OIWebEquipmentStatusCheckResponse);
        /// Web service operation 'OIWebServiceLotStart' (returns SOAP_OK or error code)
        virtual int OIWebServiceLotStart(_ns1__OIWebServiceLotStart *ns1__OIWebServiceLotStart, _ns1__OIWebServiceLotStartResponse &ns1__OIWebServiceLotStartResponse)
        { return this->OIWebServiceLotStart(NULL, NULL, ns1__OIWebServiceLotStart, ns1__OIWebServiceLotStartResponse); }
        virtual int OIWebServiceLotStart(const char *soap_endpoint, const char *soap_action, _ns1__OIWebServiceLotStart *ns1__OIWebServiceLotStart, _ns1__OIWebServiceLotStartResponse &ns1__OIWebServiceLotStartResponse);
        /// Web service operation 'OIWebEquipmentStatus' (returns SOAP_OK or error code)
        virtual int OIWebEquipmentStatus(_ns1__OIWebEquipmentStatus *ns1__OIWebEquipmentStatus, _ns1__OIWebEquipmentStatusResponse &ns1__OIWebEquipmentStatusResponse)
        { return this->OIWebEquipmentStatus(NULL, NULL, ns1__OIWebEquipmentStatus, ns1__OIWebEquipmentStatusResponse); }
        virtual int OIWebEquipmentStatus(const char *soap_endpoint, const char *soap_action, _ns1__OIWebEquipmentStatus *ns1__OIWebEquipmentStatus, _ns1__OIWebEquipmentStatusResponse &ns1__OIWebEquipmentStatusResponse);
    };
#endif
